# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# mypy: disable-error-code="var-annotated"
from __future__ import annotations

from typing import ClassVar

from appconf import AppConf

from weblate.trans import defaults


class WeblateConf(AppConf):
    # Data directory
    DATA_DIR = defaults.DEFAULT_DATA_DIR

    # Cache directory
    CACHE_DIR = defaults.DEFAULT_CACHE_DIR

    # Title of site to use
    SITE_TITLE = defaults.DEFAULT_SITE_TITLE

    # Site domain
    SITE_DOMAIN = defaults.DEFAULT_SITE_DOMAIN

    # Whether this is hosted.weblate.org
    OFFER_HOSTING = defaults.DEFAULT_OFFER_HOSTING

    # Enable remote hooks
    ENABLE_HOOKS = defaults.DEFAULT_ENABLE_HOOKS

    # Enable sharing
    ENABLE_SHARING = defaults.DEFAULT_ENABLE_SHARING

    # Default number of elements to display when pagination is active
    DEFAULT_PAGE_LIMIT = defaults.DEFAULT_PAGE_LIMIT

    # Number of nearby messages to show in each direction
    NEARBY_MESSAGES = defaults.DEFAULT_NEARBY_MESSAGES

    # Minimal number of similar messages to show
    SIMILAR_MESSAGES = defaults.DEFAULT_SIMILAR_MESSAGES

    # Enable lazy commits
    COMMIT_PENDING_HOURS = defaults.DEFAULT_COMMIT_PENDING_HOURS

    # Automatically update vcs repositories daily
    AUTO_UPDATE = defaults.DEFAULT_AUTO_UPDATE

    # List of automatic fixups
    AUTOFIX_LIST = defaults.DEFAULT_AUTOFIX_LIST

    # This is supposed to be set in the settings
    REQUIRE_LOGIN = defaults.DEFAULT_REQUIRE_LOGIN
    PUBLIC_ENGAGE = defaults.DEFAULT_PUBLIC_ENGAGE

    # Matomo, formerly known as Piwik
    MATOMO_SITE_ID = defaults.DEFAULT_MATOMO_SITE_ID
    MATOMO_URL = defaults.DEFAULT_MATOMO_URL

    # Google Analytics
    GOOGLE_ANALYTICS_ID = defaults.DEFAULT_GOOGLE_ANALYTICS_ID

    # Microsoft Clarity
    CLARITY_PROJECT_ID = defaults.DEFAULT_CLARITY_PROJECT_ID

    # Link for support portal
    GET_HELP_URL = defaults.DEFAULT_GET_HELP_URL

    # URL with status monitoring
    STATUS_URL = defaults.DEFAULT_STATUS_URL

    # URL with legal docs
    LEGAL_URL = defaults.DEFAULT_LEGAL_URL
    PRIVACY_URL = defaults.DEFAULT_PRIVACY_URL

    # Disable length limitations calculated from the source string length
    LIMIT_TRANSLATION_LENGTH_BY_SOURCE_LENGTH = (
        defaults.DEFAULT_LIMIT_TRANSLATION_LENGTH_BY_SOURCE_LENGTH
    )

    # Is the site using https
    ENABLE_HTTPS = defaults.DEFAULT_ENABLE_HTTPS

    # Hiding repository credentials
    HIDE_REPO_CREDENTIALS = defaults.DEFAULT_HIDE_REPO_CREDENTIALS

    # Hiding shared glossary components
    HIDE_SHARED_GLOSSARY_COMPONENTS = defaults.DEFAULT_HIDE_SHARED_GLOSSARY_COMPONENTS

    CREATE_GLOSSARIES = defaults.DEFAULT_CREATE_GLOSSARIES

    # Loc-kit glossary OpenRouter profile analysis (off by default)
    LOC_KIT_PROFILE_ANALYSIS_ENABLED = defaults.DEFAULT_LOC_KIT_PROFILE_ANALYSIS_ENABLED
    LOC_KIT_PROFILE_OPENROUTER_KEY = defaults.DEFAULT_LOC_KIT_PROFILE_OPENROUTER_KEY
    LOC_KIT_PROFILE_OPENROUTER_MODEL = defaults.DEFAULT_LOC_KIT_PROFILE_OPENROUTER_MODEL
    LOC_KIT_PROFILE_SAMPLE_MAX_BYTES = defaults.DEFAULT_LOC_KIT_PROFILE_SAMPLE_MAX_BYTES
    LOC_KIT_IMPORT_DRAFT_EXPIRY = defaults.DEFAULT_LOC_KIT_IMPORT_DRAFT_EXPIRY

    # LLM judge (off by default)
    JUDGE_ENABLED = defaults.DEFAULT_JUDGE_ENABLED
    JUDGE_API_KEY = defaults.DEFAULT_JUDGE_API_KEY
    JUDGE_BASE_URL = defaults.DEFAULT_JUDGE_BASE_URL
    JUDGE_MODEL_SEAT_1 = defaults.DEFAULT_JUDGE_MODEL_SEAT_1
    JUDGE_MODEL_SEAT_2 = defaults.DEFAULT_JUDGE_MODEL_SEAT_2
    JUDGE_MAX_REPAIR_ATTEMPTS = defaults.DEFAULT_JUDGE_MAX_REPAIR_ATTEMPTS
    JUDGE_BATCH_SIZE = defaults.DEFAULT_JUDGE_BATCH_SIZE
    JUDGE_MAX_UNITS_PER_RUN = defaults.DEFAULT_JUDGE_MAX_UNITS_PER_RUN
    JUDGE_REQUEST_SLEEP = defaults.DEFAULT_JUDGE_REQUEST_SLEEP
    JUDGE_REQUEST_DEADLINE = defaults.DEFAULT_JUDGE_REQUEST_DEADLINE
    JUDGE_REQUEST_IDLE_TIMEOUT = defaults.DEFAULT_JUDGE_REQUEST_IDLE_TIMEOUT
    JUDGE_TRANSPORT_RETRIES = defaults.DEFAULT_JUDGE_TRANSPORT_RETRIES
    JUDGE_PROTOCOL_RETRIES = defaults.DEFAULT_JUDGE_PROTOCOL_RETRIES
    JUDGE_TRANSIENT_HTTP_RETRIES = defaults.DEFAULT_JUDGE_TRANSIENT_HTTP_RETRIES
    JUDGE_MAX_UNPARSED_RETRY_ROUNDS = defaults.DEFAULT_JUDGE_MAX_UNPARSED_RETRY_ROUNDS
    JUDGE_RETRY_BUDGET_RATIO = defaults.DEFAULT_JUDGE_RETRY_BUDGET_RATIO
    JUDGE_MAY_APPROVE = defaults.DEFAULT_JUDGE_MAY_APPROVE
    JUDGE_REASONING_EFFORT = defaults.DEFAULT_JUDGE_REASONING_EFFORT
    JUDGE_RESPONSE_FORMAT = defaults.DEFAULT_JUDGE_RESPONSE_FORMAT
    JUDGE_STREAM = defaults.DEFAULT_JUDGE_STREAM
    JUDGE_TEMPERATURE = defaults.DEFAULT_JUDGE_TEMPERATURE
    JUDGE_MAX_TOKENS = defaults.DEFAULT_JUDGE_MAX_TOKENS
    JUDGE_REASONING_EFFORT_SEAT_1 = defaults.DEFAULT_JUDGE_REASONING_EFFORT_SEAT_1
    JUDGE_REASONING_EFFORT_SEAT_2 = defaults.DEFAULT_JUDGE_REASONING_EFFORT_SEAT_2
    JUDGE_RESPONSE_FORMAT_SEAT_1 = defaults.DEFAULT_JUDGE_RESPONSE_FORMAT_SEAT_1
    JUDGE_RESPONSE_FORMAT_SEAT_2 = defaults.DEFAULT_JUDGE_RESPONSE_FORMAT_SEAT_2
    JUDGE_STREAM_SEAT_1 = defaults.DEFAULT_JUDGE_STREAM_SEAT_1
    JUDGE_STREAM_SEAT_2 = defaults.DEFAULT_JUDGE_STREAM_SEAT_2
    JUDGE_BATCH_SIZE_SEAT_1 = defaults.DEFAULT_JUDGE_BATCH_SIZE_SEAT_1
    JUDGE_BATCH_SIZE_SEAT_2 = defaults.DEFAULT_JUDGE_BATCH_SIZE_SEAT_2
    JUDGE_TEMPERATURE_SEAT_1 = defaults.DEFAULT_JUDGE_TEMPERATURE_SEAT_1
    JUDGE_TEMPERATURE_SEAT_2 = defaults.DEFAULT_JUDGE_TEMPERATURE_SEAT_2
    JUDGE_MAX_TOKENS_SEAT_1 = defaults.DEFAULT_JUDGE_MAX_TOKENS_SEAT_1
    JUDGE_MAX_TOKENS_SEAT_2 = defaults.DEFAULT_JUDGE_MAX_TOKENS_SEAT_2
    JUDGE_DEFERRAL_ENABLED = defaults.DEFAULT_JUDGE_DEFERRAL_ENABLED
    JUDGE_DEFERRAL_MIN_INTERVAL = defaults.DEFAULT_JUDGE_DEFERRAL_MIN_INTERVAL
    JUDGE_DEFERRAL_MAX_INTERVAL = defaults.DEFAULT_JUDGE_DEFERRAL_MAX_INTERVAL
    JUDGE_DEFERRAL_SLOW_AFTER = defaults.DEFAULT_JUDGE_DEFERRAL_SLOW_AFTER
    JUDGE_DEFERRAL_MAX_UNITS_PER_PASS = (
        defaults.DEFAULT_JUDGE_DEFERRAL_MAX_UNITS_PER_PASS
    )
    JUDGE_DEFERRAL_CIRCUIT_FAILURE_THRESHOLD = (
        defaults.DEFAULT_JUDGE_DEFERRAL_CIRCUIT_FAILURE_THRESHOLD
    )
    JUDGE_DEFERRAL_CIRCUIT_OPEN_SECONDS = (
        defaults.DEFAULT_JUDGE_DEFERRAL_CIRCUIT_OPEN_SECONDS
    )
    JUDGE_DEFERRAL_TOKEN_BUCKET_CAPACITY = (
        defaults.DEFAULT_JUDGE_DEFERRAL_TOKEN_BUCKET_CAPACITY
    )
    JUDGE_DEFERRAL_TOKEN_BUCKET_REFILL_PER_SECOND = (
        defaults.DEFAULT_JUDGE_DEFERRAL_TOKEN_BUCKET_REFILL_PER_SECOND
    )
    JUDGE_DEFERRAL_OPERATOR_STOPPED = defaults.DEFAULT_JUDGE_DEFERRAL_OPERATOR_STOPPED
    JUDGE_REQUEST_ATTEMPT_RETENTION_DAYS = (
        defaults.DEFAULT_JUDGE_REQUEST_ATTEMPT_RETENTION_DAYS
    )
    LLM_USAGE_LOG_RETENTION_DAYS = defaults.DEFAULT_LLM_USAGE_LOG_RETENTION_DAYS

    # Default committer
    DEFAULT_COMMITER_EMAIL = defaults.DEFAULT_COMMITER_EMAIL
    DEFAULT_COMMITER_NAME = defaults.DEFAULT_COMMITER_NAME

    DEFAULT_TRANSLATION_PROPAGATION = defaults.DEFAULT_TRANSLATION_PROPAGATION
    DEFAULT_MERGE_STYLE = defaults.DEFAULT_MERGE_STYLE

    DEFAULT_ACCESS_CONTROL = defaults.DEFAULT_ACCESS_CONTROL
    DEFAULT_RESTRICTED_COMPONENT = defaults.DEFAULT_RESTRICTED_COMPONENT
    DEFAULT_SHARED_TM = defaults.DEFAULT_SHARED_TM
    DEFAULT_AUTOCLEAN_TM = defaults.DEFAULT_AUTOCLEAN_TM
    DEFAULT_TRANSLATION_REVIEW = defaults.DEFAULT_TRANSLATION_REVIEW
    DEFAULT_SOURCE_REVIEW = defaults.DEFAULT_SOURCE_REVIEW

    DEFAULT_PUSH_ON_COMMIT = defaults.DEFAULT_PUSH_ON_COMMIT
    DEFAULT_AUTO_LOCK_ERROR = defaults.DEFAULT_AUTO_LOCK_ERROR
    DEFAULT_VCS = defaults.DEFAULT_VCS
    DEFAULT_COMMIT_MESSAGE = defaults.DEFAULT_COMMIT_MESSAGE

    DEFAULT_ADD_MESSAGE = defaults.DEFAULT_ADD_MESSAGE

    DEFAULT_DELETE_MESSAGE = defaults.DEFAULT_DELETE_MESSAGE

    DEFAULT_MERGE_MESSAGE = defaults.DEFAULT_MERGE_MESSAGE

    DEFAULT_ADDON_MESSAGE = defaults.DEFAULT_ADDON_MESSAGE
    DEFAULT_PULL_MESSAGE = defaults.DEFAULT_PULL_MESSAGE

    # Billing
    INVOICE_PATH = defaults.DEFAULT_INVOICE_PATH
    INVOICE_PATH_LEGACY = defaults.DEFAULT_INVOICE_PATH_LEGACY
    VAT_RATE = defaults.DEFAULT_VAT_RATE
    SUPPORT_API_URL = defaults.DEFAULT_SUPPORT_API_URL

    # Rate limiting
    IP_BEHIND_REVERSE_PROXY = defaults.DEFAULT_IP_BEHIND_REVERSE_PROXY
    IP_PROXY_HEADER = defaults.DEFAULT_IP_PROXY_HEADER
    IP_PROXY_OFFSET = defaults.DEFAULT_IP_PROXY_OFFSET

    # Authentication
    AUTH_TOKEN_VALID = defaults.DEFAULT_AUTH_TOKEN_VALID
    AUTH_LOCK_ATTEMPTS = defaults.DEFAULT_AUTH_LOCK_ATTEMPTS
    AUTH_PASSWORD_DAYS = defaults.DEFAULT_AUTH_PASSWORD_DAYS

    # Mail customization
    ADMINS_CONTACT: ClassVar[list] = list(defaults.DEFAULT_ADMINS_CONTACT)
    ADMINS_HOSTING: ClassVar[list] = list(defaults.DEFAULT_ADMINS_HOSTING)
    ADMINS_BILLING: ClassVar[list] = list(defaults.DEFAULT_ADMINS_BILLING)

    # Special chars for visual keyboard
    SPECIAL_CHARS = defaults.DEFAULT_SPECIAL_CHARS

    DEFAULT_ADDONS: ClassVar[dict] = dict(defaults.DEFAULT_ADDONS)

    REPOSITORY_ALERT_THRESHOLD = defaults.DEFAULT_REPOSITORY_ALERT_THRESHOLD
    UNUSED_ALERT_DAYS = defaults.DEFAULT_UNUSED_ALERT_DAYS
    BACKGROUND_TASKS = defaults.DEFAULT_BACKGROUND_TASKS

    SINGLE_PROJECT = defaults.DEFAULT_SINGLE_PROJECT
    LICENSE_EXTRA: ClassVar[list] = list(defaults.DEFAULT_LICENSE_EXTRA)
    LICENSE_FILTER = defaults.DEFAULT_LICENSE_FILTER
    LICENSE_REQUIRED = defaults.DEFAULT_LICENSE_REQUIRED
    WEBSITE_REQUIRED = defaults.DEFAULT_WEBSITE_REQUIRED
    # Enable or disable website availability checks and alerts
    # Set to False to disable broken website alerts
    WEBSITE_ALERTS_ENABLED = defaults.DEFAULT_WEBSITE_ALERTS_ENABLED
    FONTS_CDN_URL = defaults.DEFAULT_FONTS_CDN_URL
    PROJECT_BACKUP_KEEP_DAYS = defaults.DEFAULT_PROJECT_BACKUP_KEEP_DAYS
    PROJECT_BACKUP_KEEP_COUNT = defaults.DEFAULT_PROJECT_BACKUP_KEEP_COUNT
    REPORT_EXPIRY = defaults.DEFAULT_REPORT_EXPIRY

    EXTRA_HTML_HEAD = defaults.DEFAULT_EXTRA_HTML_HEAD

    IP_ADDRESSES: ClassVar[list] = list(defaults.DEFAULT_IP_ADDRESSES)

    class Meta:
        prefix = ""
