# Copyright © HCGameLoc
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.7 on 2026-08-14 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0098_loc_kit_import_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="lockitimportdraft",
            name="target_component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loc_kit_update_drafts",
                to="trans.component",
            ),
        ),
    ]
