# Generated by Django 6.0.7 on 2026-08-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0099_loc_kit_draft_target_component"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMUsageLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("model", models.CharField(db_index=True, max_length=200)),
                ("project_slug", models.CharField(blank=True, max_length=200)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=12, null=True
                    ),
                ),
                ("response_id", models.CharField(blank=True, max_length=255)),
                ("cached_tokens", models.IntegerField(default=0)),
                ("reasoning_tokens", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
