# Copyright © HCGameLoc
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.7 on 2026-08-20 04:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0100_llmusagelog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgeVerdict",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_verdict",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Pass"),
                            ("flag", "Flag"),
                            ("reject", "Reject"),
                            ("unparsed", "Unparsed"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "max_severity",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("minor", "Minor"),
                            ("major", "Major"),
                            ("critical", "Critical"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("unparsed", models.BooleanField(default=False)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("back_translation", models.TextField(blank=True)),
                ("judge_model", models.CharField(max_length=200)),
                ("seat", models.SmallIntegerField()),
                ("attempt", models.SmallIntegerField(default=0)),
                ("target_hash", models.CharField(max_length=64)),
                ("context_hash", models.CharField(max_length=64)),
                ("run_id", models.UUIDField(default=uuid.uuid4)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accepted_as_is", "Accepted As Is"),
                            ("sent_back", "Sent Back"),
                            ("escalated", "Escalated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resolution_reason", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="judge_resolutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge_verdicts",
                        to="trans.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Judge verdict",
                "verbose_name_plural": "Judge verdicts",
                "indexes": [
                    models.Index(
                        fields=["unit", "-timestamp"], name="judge_unit_recent_idx"
                    ),
                    models.Index(
                        fields=["unit", "target_hash", "-timestamp"],
                        name="judge_unit_target_idx",
                    ),
                    models.Index(fields=["run_id"], name="judge_run_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("unit", "run_id", "attempt", "seat"),
                        name="judge_one_vote_per_seat",
                    )
                ],
            },
        ),
    ]
