# Copyright © 2026 Weblate contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.7 on 2026-08-22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0101_judge_verdict"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentSpreadsheetImportDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("session_key", models.CharField(max_length=40)),
                ("source_filename", models.CharField(max_length=500)),
                ("uploaded", models.FileField(blank=True, upload_to="")),
                ("preview_json", models.TextField(blank=True)),
                ("baseline_json", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("preview-ready", "Preview ready"),
                            ("consumed", "Consumed"),
                        ],
                        default="preview-ready",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multilingual_spreadsheet_import_drafts",
                        to="trans.component",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_spreadsheet_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        )
    ]
