# Copyright © 2026 Weblate contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.7 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0102_component_spreadsheet_import_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmusagelog",
            name="batch_size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="llmusagelog",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("applied", "applied"),
                    ("partial", "partial"),
                    ("refused", "refused"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
