# Copyright © HCGameLoc
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.7 on 2026-08-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0103_llmusagelog_batch_size_llmusagelog_outcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgeverdict",
            name="target_storage_hash",
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
    ]
