# Copyright © HCGameLoc
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.7 on 2026-08-27 10:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0106_merge_0103_llmusagelog_batch_size"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgeRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("started", models.DateTimeField(blank=True, null=True)),
                ("finished", models.DateTimeField(blank=True, null=True)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("translation", "Translation"),
                            ("component", "Component"),
                            ("project", "Project"),
                            ("workspace", "Workspace"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scope_id", models.CharField(max_length=64)),
                ("scope_label", models.CharField(max_length=255)),
                ("scope_path", models.CharField(max_length=500)),
                ("requested_query", models.TextField(blank=True)),
                ("requested_mode", models.CharField(max_length=20)),
                ("cap", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("failure", models.TextField(blank=True)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="judge_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Judge run",
                "verbose_name_plural": "Judge runs",
            },
        ),
        migrations.CreateModel(
            name="JudgeRunUnit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_id_snapshot", models.BigIntegerField()),
                ("translation_id", models.BigIntegerField()),
                ("component_id", models.BigIntegerField()),
                ("project_id", models.BigIntegerField()),
                ("input_target", models.JSONField(default=list)),
                ("input_target_hash", models.CharField(max_length=64)),
                ("context_hash", models.CharField(max_length=64)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("minor", "Minor"),
                            ("major", "Major"),
                            ("critical", "Critical"),
                            ("unparsed", "Unparsed"),
                            ("skipped", "Skipped"),
                            ("stale-conflict", "Stale Conflict"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "skip_reason",
                    models.CharField(
                        blank=True,
                        choices=[("permission", "Permission"), ("cap", "Cap")],
                        max_length=20,
                    ),
                ),
                (
                    "repair_status",
                    models.CharField(
                        choices=[
                            ("not-attempted", "Not Attempted"),
                            ("no-candidate", "No Candidate"),
                            ("applied", "Applied"),
                            ("rolled-back", "Rolled Back"),
                        ],
                        default="not-attempted",
                        max_length=20,
                    ),
                ),
                (
                    "initial_severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "none"),
                            ("minor", "minor"),
                            ("major", "major"),
                            ("critical", "critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "final_severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "none"),
                            ("minor", "minor"),
                            ("major", "major"),
                            ("critical", "critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("before_target", models.JSONField(default=list)),
                ("after_target", models.JSONField(default=list)),
                ("cached", models.BooleanField(default=False)),
                ("projection_succeeded", models.BooleanField(default=False)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trans.judgerun"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="judge_run_units",
                        to="trans.unit",
                    ),
                ),
                (
                    "verdict",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="run_outcomes",
                        to="trans.judgeverdict",
                    ),
                ),
            ],
            options={
                "verbose_name": "Judge run unit",
                "verbose_name_plural": "Judge run units",
            },
        ),
        migrations.AddIndex(
            model_name="judgerun",
            index=models.Index(
                fields=["actor", "-created"], name="judge_run_actor_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="judgerun",
            index=models.Index(
                fields=["scope_type", "scope_id", "-created"],
                name="judge_run_scope_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="judgerun",
            index=models.Index(
                fields=["status", "-created"], name="judge_run_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="judgerununit",
            index=models.Index(fields=["run", "outcome"], name="judge_run_outcome_idx"),
        ),
        migrations.AddIndex(
            model_name="judgerununit",
            index=models.Index(
                fields=["run", "repair_status"], name="judge_run_repair_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="judgerununit",
            constraint=models.UniqueConstraint(
                fields=("run", "unit_id_snapshot"), name="judge_run_one_unit"
            ),
        ),
    ]
