# Copyright © HCGameLoc
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.7 on 2026-08-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0107_judgerun_judgerununit_judgerun_judge_run_actor_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgeverdict",
            name="instruction",
            field=models.TextField(blank=True),
        ),
    ]
