# Generated by Django 6.0.7 on 2026-09-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0112_judge_run_unit_deferred_outcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmusagelog",
            name="component_id_snapshot",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="llmusagelog",
            name="component_slug",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="llmusagelog",
            name="project_id_snapshot",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="llmusagelog",
            name="service",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="llmusagelog",
            name="target_language_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="llmusagelog",
            name="cost_usd",
            field=models.DecimalField(
                blank=True, decimal_places=18, max_digits=24, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="llmusagelog",
            index=models.Index(
                fields=[
                    "project_id_snapshot",
                    "component_id_snapshot",
                    "target_language_code",
                    "service",
                    "operation",
                    "-created_at",
                ],
                name="llm_usage_scope_recent_idx",
            ),
        ),
    ]
