# Copyright © HCGameLoc
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.7 on 2026-09-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0113_llm_usage_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judgeadaptivestate",
            name="last_failure_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("transport", "Transport"),
                    ("deadline", "Deadline"),
                    ("response-too-large", "Response Too Large"),
                    ("http-auth", "Http Auth"),
                    ("http-rate-limit", "Http Rate Limit"),
                    ("http-server", "Http Server"),
                    ("http-request-invalid", "Http Request Invalid"),
                    ("http-other", "Http Other"),
                    ("empty-response", "Empty Response"),
                    ("invalid-json", "Invalid Json"),
                    ("invalid-envelope", "Invalid Envelope"),
                    ("segment-count", "Segment Count"),
                    ("invalid-segment", "Invalid Segment"),
                    ("finish-length", "Finish Length"),
                    ("unknown", "Unknown"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="judgedeferral",
            name="last_failure_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("transport", "Transport"),
                    ("deadline", "Deadline"),
                    ("response-too-large", "Response Too Large"),
                    ("http-auth", "Http Auth"),
                    ("http-rate-limit", "Http Rate Limit"),
                    ("http-server", "Http Server"),
                    ("http-request-invalid", "Http Request Invalid"),
                    ("http-other", "Http Other"),
                    ("empty-response", "Empty Response"),
                    ("invalid-json", "Invalid Json"),
                    ("invalid-envelope", "Invalid Envelope"),
                    ("segment-count", "Segment Count"),
                    ("invalid-segment", "Invalid Segment"),
                    ("finish-length", "Finish Length"),
                    ("unknown", "Unknown"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="judgerequestattempt",
            name="failure_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("transport", "Transport"),
                    ("deadline", "Deadline"),
                    ("response-too-large", "Response Too Large"),
                    ("http-auth", "Http Auth"),
                    ("http-rate-limit", "Http Rate Limit"),
                    ("http-server", "Http Server"),
                    ("http-request-invalid", "Http Request Invalid"),
                    ("http-other", "Http Other"),
                    ("empty-response", "Empty Response"),
                    ("invalid-json", "Invalid Json"),
                    ("invalid-envelope", "Invalid Envelope"),
                    ("segment-count", "Segment Count"),
                    ("invalid-segment", "Invalid Segment"),
                    ("finish-length", "Finish Length"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
    ]
