# Copyright © HCGameLoc
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.7 on 2026-09-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0114_judge_request_invalid_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judgerununit",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("passed", "Passed"),
                    ("minor", "Minor"),
                    ("major", "Major"),
                    ("critical", "Critical"),
                    ("unparsed", "Unparsed"),
                    ("deferred", "Deferred"),
                    ("refused", "Refused"),
                    ("skipped", "Skipped"),
                    ("stale-conflict", "Stale Conflict"),
                ],
                max_length=20,
            ),
        ),
    ]
