# Copyright © HCGameLoc
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.7 on 2026-09-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0115_judge_run_unit_refused_outcome"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="judgedeferral",
            index=models.Index(
                fields=["state", "closed_at"], name="judge_deferral_closed_idx"
            ),
        ),
    ]
