# Copyright © HCGameLoc
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.7 on 2026-09-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0118_judge_run_unit_candidate_stored"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgeverdict",
            name="generation_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("existing", "Existing"),
                    ("stale", "Stale"),
                    ("denied", "Denied"),
                    ("invalid-verdict", "Invalid Verdict"),
                    ("resolved", "Resolved"),
                    ("max-length", "Max Length"),
                    ("no-engine", "No Engine"),
                    ("busy", "Busy"),
                    ("failed", "Failed"),
                    ("drift", "Drift"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="judgeverdict",
            name="generation_outcome_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
