# Generated by Django 6.0.7 on 2026-09-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0135_judge_run_unit_untranslated_skip"),
    ]

    operations = [
        migrations.AddField(
            model_name="producerrun",
            name="preparation_phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("preparing", "Preparing"),
                    ("ready", "Ready"),
                    ("blocked", "Blocked"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="producerrun",
            name="preparation_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="judgerununit",
            name="skip_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("permission", "Permission"),
                    ("cap", "Cap"),
                    ("untranslated", "Untranslated"),
                    ("mt-prerequisite", "Mt Prerequisite"),
                ],
                max_length=20,
            ),
        ),
    ]
