# Copyright © HCGameLoc
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Generated by Django 6.0.7 on 2026-09-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0135_judge_run_unit_untranslated_skip"),
    ]

    operations = [
        migrations.AddField(
            model_name="producerrun",
            name="preparation_phase",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="producerrun",
            name="preparation_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
