# Copyright © HCGameLoc
#
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by Django 6.0.7 on 2026-09-22 13:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lang", "0007_alter_language_code"),
        ("trans", "0137_producer_run_full_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RepeatGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_forms", models.JSONField(default=list)),
                ("source_hash", models.CharField(max_length=64)),
                ("plural_number", models.PositiveSmallIntegerField()),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("shared_target", models.JSONField(blank=True, default=list)),
                ("decision_origin", models.CharField(blank=True, max_length=40)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repeat_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "required_db_vendor": "postgresql",
            },
        ),
        migrations.CreateModel(
            name="RepeatDecisionEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("apply", "Apply repeat decision"),
                            ("independent", "Keep repeats independent"),
                            ("undo", "Undo repeat decision"),
                        ],
                        max_length=20,
                    ),
                ),
                ("group_revision", models.PositiveBigIntegerField()),
                ("policy_revision", models.PositiveBigIntegerField()),
                ("snapshot", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("reason", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repeat_decision_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision_events",
                        to="trans.repeatgroup",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "required_db_vendor": "postgresql",
            },
        ),
        migrations.CreateModel(
            name="RepeatPolicy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repeat_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "components",
                    models.ManyToManyField(
                        related_name="repeat_policies", to="trans.component"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repeat_policies",
                        to="trans.project",
                    ),
                ),
                (
                    "source_labels",
                    models.ManyToManyField(
                        blank=True, related_name="repeat_policies", to="trans.label"
                    ),
                ),
                (
                    "source_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repeat_source_policies",
                        to="lang.language",
                    ),
                ),
                (
                    "target_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repeat_target_policies",
                        to="lang.language",
                    ),
                ),
            ],
            options={
                "required_db_vendor": "postgresql",
            },
        ),
        migrations.AddField(
            model_name="repeatgroup",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="trans.repeatpolicy",
            ),
        ),
        migrations.CreateModel(
            name="RepeatMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translation_id_snapshot", models.PositiveBigIntegerField()),
                ("id_hash_snapshot", models.BigIntegerField()),
                ("source_forms_snapshot", models.JSONField(default=list)),
                ("context_snapshot", models.TextField(default="")),
                ("constraints_snapshot", models.JSONField(default=dict)),
                ("fingerprint", models.CharField(max_length=64)),
                (
                    "mode",
                    models.CharField(
                        choices=[("shared", "Shared"), ("independent", "Independent")],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=80)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("stale_at", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="trans.repeatgroup",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repeat_memberships",
                        to="trans.unit",
                    ),
                ),
            ],
            options={
                "required_db_vendor": "postgresql",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "unit"),
                        name="repeat_membership_group_unit_unique",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="repeatpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_language", models.F("target_language")), _negated=True
                ),
                name="repeat_policy_languages_differ",
            ),
        ),
        migrations.AddConstraint(
            model_name="repeatgroup",
            constraint=models.UniqueConstraint(
                fields=("policy", "source_hash", "plural_number"),
                name="repeat_group_policy_source_plural_unique",
            ),
        ),
    ]
