# Copyright © HCGameLoc
#
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by Django 6.0.7 on 2026-09-22 14:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0139_repeat_apply_actions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RepeatRecommendationRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("snapshot", models.JSONField(default=dict)),
                ("snapshot_fingerprint", models.CharField(max_length=64)),
                ("profile_fingerprint", models.CharField(max_length=64)),
                ("prompt_fingerprint", models.CharField(max_length=64)),
                ("request_cap", models.PositiveIntegerField()),
                ("requests_reserved", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("failure", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repeat_recommendation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_runs",
                        to="trans.repeatpolicy",
                    ),
                ),
            ],
            options={
                "required_db_vendor": "postgresql",
            },
        ),
        migrations.CreateModel(
            name="RepeatRecommendationResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_revision", models.PositiveBigIntegerField()),
                ("snapshot_fingerprint", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=30)),
                ("target", models.JSONField(blank=True, default=list)),
                ("exclusions", models.JSONField(blank=True, default=list)),
                ("rationale", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="trans.repeatgroup",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="trans.repeatrecommendationrun",
                    ),
                ),
            ],
            options={
                "required_db_vendor": "postgresql",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "group"),
                        name="repeat_recommendation_result_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RepeatRecommendationAttempt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordinal", models.PositiveIntegerField()),
                ("request_snapshot", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("sent", "Sent"),
                            ("completed", "Completed"),
                            ("unknown", "Unknown"),
                            ("failed", "Failed"),
                        ],
                        default="reserved",
                        max_length=20,
                    ),
                ),
                ("response", models.JSONField(default=dict)),
                ("failure", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="trans.repeatrecommendationrun",
                    ),
                ),
            ],
            options={
                "required_db_vendor": "postgresql",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "ordinal"),
                        name="repeat_recommendation_attempt_unique",
                    )
                ],
            },
        ),
    ]
