# Copyright © HCGameLoc
#
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by Django 6.0.7 on 2026-09-22 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0140_repeat_recommendations"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmusagelog",
            name="repeat_recommendation_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usage_logs",
                to="trans.repeatrecommendationrun",
            ),
        ),
        migrations.AlterField(
            model_name="llmusagelog",
            name="operation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("translation", "Translation"),
                    ("judge", "Judge"),
                    ("repeat_recommend", "Repeat Recommend"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
