# Copyright © HCGameLoc
#
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by Django 6.0.7 on 2026-09-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0141_repeat_recommendation_usage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repeatrecommendationrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("unknown", "Unknown"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
    ]
