# Generated by Django 6.0.7 on 2026-09-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0138_alter_change_action"),
        ("trans", "0142_repeat_recommendation_unknown"),
    ]

    operations = []
