# Copyright © HCGameLoc
#
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by Django 6.0.7 on 2026-09-24 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trans", "0144_alter_change_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="repeatrecommendationattempt",
            name="deadline_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repeatrecommendationattempt",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repeatrecommendationresult",
            name="attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="results",
                to="trans.repeatrecommendationattempt",
            ),
        ),
        migrations.AddField(
            model_name="repeatrecommendationresult",
            name="context_fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="repeatrecommendationrun",
            name="unsent_groups",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="repeatrecommendationresult",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attempt__isnull", False)),
                fields=("attempt", "group"),
                name="repeat_recommendation_attempt_group_unique",
            ),
        ),
    ]
