# Generated by Django 6.0.7 on 2026-09-24 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trans", "0145_repeat_recommendation_context"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RepeatBulkRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("apply", "Apply repeat decisions"),
                            ("undo", "Undo repeat decisions"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "review_nonce",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total", models.PositiveIntegerField(default=0)),
                ("done", models.PositiveIntegerField(default=0)),
                ("written", models.PositiveIntegerField(default=0)),
                ("restored", models.PositiveIntegerField(default=0)),
                ("conflict", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("failure_code", models.CharField(blank=True, max_length=80)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repeat_bulk_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "apply_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="undo_runs",
                        to="trans.repeatbulkrun",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_runs",
                        to="trans.repeatpolicy",
                    ),
                ),
            ],
            options={
                "required_db_vendor": "postgresql",
            },
        ),
        migrations.CreateModel(
            name="RepeatBulkItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordinal", models.PositiveIntegerField()),
                ("group_identity", models.JSONField(default=dict)),
                ("decision", models.JSONField(default=dict)),
                ("context_fingerprint", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                            ("undone", "Undone"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("outcome", models.JSONField(default=dict)),
                ("failure_code", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "apply_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="undo_bulk_items",
                        to="trans.repeatdecisionevent",
                    ),
                ),
                (
                    "decision_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_items",
                        to="trans.repeatdecisionevent",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_items",
                        to="trans.repeatgroup",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_items",
                        to="trans.repeatrecommendationresult",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="trans.repeatbulkrun",
                    ),
                ),
            ],
            options={
                "required_db_vendor": "postgresql",
            },
        ),
        migrations.AddConstraint(
            model_name="repeatbulkrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("review_nonce", ""), _negated=True),
                fields=("review_nonce",),
                name="repeat_bulk_run_nonce_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="repeatbulkrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("apply_run__isnull", False)),
                fields=("apply_run",),
                name="repeat_bulk_run_single_undo",
            ),
        ),
        migrations.AddConstraint(
            model_name="repeatbulkitem",
            constraint=models.UniqueConstraint(
                fields=("run", "ordinal"), name="repeat_bulk_item_ordinal_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="repeatbulkitem",
            constraint=models.UniqueConstraint(
                fields=("run", "group_identity"), name="repeat_bulk_item_group_unique"
            ),
        ),
    ]
